# Site settings
title: Anna.log
description: "blog"
url: "https://haeunchoi-dev.github.io./"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: haeun choi
  #  url:
  email: haeunchoi.dev@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
#permalink: /:year-:month-:day/:title
permalink: /:categories/:year-:month-:day/:slug
paginate: 5
# Excludes
# exclude: [Gemfile, Gemfile.lock]
# Disqus (Set to your disqus id)
# disqus: jekyll-tale
